### ISSUE TITLE
status update

### ISSUE THREAD

**Issue by travlytle** [romdnop/j1708#1]
Hi,

Just wanted to see if this has been working?  I've tried to run it and I get the following:

Traceback (most recent call last):
  File "C:\Users\a1062371\Desktop\j1708\j1708-master\j1708_com_receive.py", line 71, in <module>
    handle_data(reading)
  File "C:\Users\a1062371\Desktop\j1708\j1708-master\j1708_com_receive.py", line 20, in handle_data
    data = [ord(i) for i in data]
  File "C:\Users\a1062371\Desktop\j1708\j1708-master\j1708_com_receive.py", line 20, in <listcomp>
    data = [ord(i) for i in data]
TypeError: ord() expected string of length 1, but int found

I am trying on windows 7, with updating the following line only:
com.port = "COM24"

**Comment by romdnop** [comment]
Hi travlytle,

Sorry, I have to admit that I missed your message.

_j1708_com_receive.py_ is expected to be run with a preliminary knowledge of J1708 traffic already present on the bus. It is just a script, and not a library. 

I assume that the issue was in data format. The expected data to be passed into 'handle_data()' is obtained from com.readline(), which returns [io.IOBase.readline](https://docs.python.org/3/library/io.html#io.IOBase.readline), basically just a line from the stream.

In case of the 'receive' script the line is defined not by a terminator symbol, but by a delay which is set in com.timeout, as well as number of characters received.

I would suggest to play with the timeout, and actually check that there are messages being transmitted on the bus. The easiest way is to use [hterm](https://www.der-hammer.info/pages/terminal.html) which is available for Windows. It allows to separate messages by a given timeout, number of bytes as well as a terminator.

I also added [link](https://www.kvaser.com/about-can/can-standards/j1708/) to short description of the protocol that can be found online.

I hope it helps.


Kind Regards,
romdnop
